name: repository_generation
description: Create Event, State and Repo classes
version: 1.0.0
author: Yannick Coulombe <ycoulombepro@gmail.com>
homepage: https://github.com/yancoupro/dart-repo-generator

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.5
  repository_annotations:
    path: ../repository_annotations/

dev_dependencies:
  test: 1.14.3
  build_test: ^1.0.0
  build_runner: 1.10.0
